### ISSUE TITLE
Use pyclean v3 features

### ISSUE THREAD

**Issue by bittner** [alxdrcirilo/RamachanDraw#12]
I saw [you use pyclean](https://github.com/alxdrcirilo/ramachandraw/blob/master/Makefile#L3-L5) in your `Makefile`.

Note that you can now simplify that code, leveraging modern pyclean features:

```diff
--- a/Makefile
+++ b/Makefile

 clean:
-	pyclean .
-	rm -rf .pdb/ obsolete/ .mypy_cache/ .pytest_cache/ .ruff_cache/ htmlcov/ .coverage
+	pyclean . --debris --erase .pdb/**/* .pdb/ obsolete/**/* obsolete/
```

The `--debris` option will take care of all commonly known build files and folders. With `--erase` you can clean up arbitrary files.

**Note:** Add a `--yes` to the end of the line if you're sure the `--erase` works as you expected. Try with `--verbose --dry-run` first, maybe.

If you think `.pdb` should also be a `--debris` target feel free to [open an issue](https://github.com/bittner/pyclean/issues) or submit a PR on the pyclean repository.

Thanks for using PyClean! :cake: 

## Reference

- See [tox.ini](https://github.com/bittner/pyclean/blob/main/tox.ini#L25-L29) (PyClean project)

**Comment by alxdrcirilo** [comment]
Hi @bittner 👋

Love PyClean!
Thank you for taking the time to recommend the changes! I will edit the `Makefile` to reflect them.
