### ISSUE TITLE
fetch_pdb "desired structure doesn't exist"

### ISSUE THREAD

**Issue by Wenxi-Zhang** [alxdrcirilo/RamachanDraw#17]
Hello! I tried this code:
from ramachandraw.utils import fetch_pdb
pdb_id = "1s76"
fetch_pdb(pdb_id)

and get this result: Desired structure doesn't exist  '.pdb/pdb1s76.ent'
I also tried several other proteins and all of them getting the same result. Is there any reason for this error? 

I tried the following code to confirm these proteins actually exist on the PDB website:
import requests

pdb_id = "1S76"
url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
response = requests.get(url)

if response.status_code == 200:
    print("PDB file found and accessible!")
else:
    print("PDB file not found. Status code:", response.status_code)

and get result: PDB file found and accessible!

Thanks for help!

**Comment by alxdrcirilo** [comment]
Hi 👋

Thanks for submitting your issue. I could not reproduce your issue unfortunately.

Some questions to help you troubleshoot this:
- Which OS are you running?
- Which Python version are you using?
- Which version of `ramachandraw` are you using?
- Could you try deleting the local `.pdb` directory and run your script again?

**Comment by Wenxi-Zhang** [comment]
Hi! I'm using MacBook Air with Sonoma 14.5, python 3.12.6. All my friends are having the same result. I don't have a local file with .pdb directory though, could you give a little more info on how to do that?

For the `ramachandraw` version, we used Jupyter notebook and the following code:
`%pip install RamachanDraw`
which returns:
Requirement already satisfied: RamachanDraw in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (1.0.1)
Requirement already satisfied: biopython<2.0,>=1.83 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from RamachanDraw) (1.84)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.3 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from RamachanDraw) (3.9.2)
Requirement already satisfied: numpy in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from biopython<2.0,>=1.83->RamachanDraw) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from matplotlib<4.0.0,>=3.8.3->RamachanDraw) (1.3.0)
Requirement already satisfied: cycler>=0.10 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from matplotlib<4.0.0,>=3.8.3->RamachanDraw) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from matplotlib<4.0.0,>=3.8.3->RamachanDraw) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from matplotlib<4.0.0,>=3.8.3->RamachanDraw) (1.4.7)
Requirement already satisfied: packaging>=20.0 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from matplotlib<4.0.0,>=3.8.3->RamachanDraw) (24.1)
Requirement already satisfied: pillow>=8 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from matplotlib<4.0.0,>=3.8.3->RamachanDraw) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from matplotlib<4.0.0,>=3.8.3->RamachanDraw) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from matplotlib<4.0.0,>=3.8.3->RamachanDraw) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in [/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages) (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.8.3->RamachanDraw) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

and then we used
`import ramachandraw`
`from ramachandraw.utils import fetch_pdb`
`pdb_id = "1s76.pdb"`
`fetch_pdb(pdb_id, file_format = "pdb")`
and get:
Desired structure doesn't exist
'.pdb/pdb1s76.pdb.ent'

I also tried this code:
`from Bio.PDB import *`
`pl = PDBList()`
`pl.retrieve_pdb_file("1s76", file_format='pdb')`
and get this:
Downloading PDB structure '1s76'...
Desired structure doesn't exist

**Comment by alxdrcirilo** [comment]
You are providing an invalid `pdb_id`, it should be `pdb_id = "1s76"`.

**Comment by Wenxi-Zhang** [comment]
Hi! I changed my python environment to 3.9.6 and it works now. It also works on google colab. Seems like python 3.12.6 does not support this function.
(I initially used `pdb_id = "1s76"` and it also didn't work.)

**Comment by alxdrcirilo** [comment]
I am unable to reproduce your issue on my machine running Python 3.12.6.
I have a feeling this is related to your environment.

Glad you figured it out either way.
