### ISSUE TITLE
What percentage of residues are in favored, allowed, generously allowed, and disallowed region?

### ISSUE THREAD

**Issue by SShaminur** [alxdrcirilo/RamachanDraw#4]
Hi, Thank you for your excellent tools. 
But how I can assess my local pdb, like what percentage and which residues are in favored, allowed, generously allowed, and disallowed region?

Thank you

**Comment by alxdrcirilo** [comment]
Hi there!

Thank you so much for your kind words :)

Local PDB files (that RamachanDraw downloaded using the *fetch* function) are located in the “PDB” folder within the working directory (i.e. where you are running python from).

With regard to the percentage and type of aa residues within each region, I unfortunately do not plan on adding that feature for the foreseeable future as I have other critical projects going on at the moment. For now, RamachanDraw is merely a tool to visualize the aa residues. You can use the *phi_psi* function to get a list of the torsion angles for each residue in the PDB and use your own filters (allowed/disallowed regions) on that for now.

**Comment by SShaminur** [comment]
Thank you very much.
