### ISSUE TITLE
Documentation Doesn't Mention Batch Plotting

### ISSUE THREAD

**Issue by noahlb123** [alxdrcirilo/RamachanDraw#5]
The documentation defines the pdb_file parameter in the Plot() function as follows:

"pdb_file (str): PDB id corresponding to the PDB entry to be downloaded"

The documentation does not mention that the pdb_file parameter can also be a list of PDB strings, in which case the separate PDB files will be plotted as a batch on the same plot, each with their own color key.

To find this functionality I had to look through the source code.

**Comment by alxdrcirilo** [comment]
Thank you for reporting this.

I updated the README.md accordingly.
